name: Python Application Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover || echo "No tests found, continuing..."

    - name: Run the Flask app (for testing purposes)
      run: |
        nohup flask run --host=0.0.0.0 --port=3000 &  # Run Flask in the background
        sleep 10  # Wait for the server to start

    - name: Check if Flask is running
      run: |
        for i in {1..10}; do
          if curl -I http://127.0.0.1:3000; then
            echo "Flask app is running"
            break
          else
            echo "Waiting for Flask app to start..."
            sleep 2
          fi
        done
